version: '3.8'

services:
  proxy-app:
    build: .
    container_name: proxy_app
    restart: always
    expose:
      - "3000"          # internal port only
    environment:
      - DISABLE_CACHE=true
    networks:
      - lordflix_net

networks:
  lordflix_net:
    external: true
